"""empty message

Revision ID: 017423263dce
Revises: 
Create Date: 2021-06-30 12:57:56.506132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017423263dce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('profile_image', sa.String(length=256), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.Integer(), nullable=True),
    sa.Column('accepter', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accepter'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giftlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('gift_name', sa.String(length=100), nullable=False),
    sa.Column('gift_description', sa.String(length=256), nullable=False),
    sa.Column('gift_link', sa.String(length=256), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['giftlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gifts')
    op.drop_table('giftlists')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
